name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: studentperformancejk
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: testdockerjitesh.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: 'Build and push Docker image'
      run: |
        docker system prune -f
        docker build --no-cache . -t testdockerjitesh.azurecr.io/studentperformance:latest
        docker push testdockerjitesh.azurecr.io/studentperformance:latest

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'testdockerjitesh.azurecr.io/studentperformance:latest'